eight_points_guzzle:
    logging: true
        clients:
            api:
                base_url: "http://localhost:3000"
                options:
                    headers:
                        Accept: "application/json"