security:
    encoders:
        App\Entity\User: bcrypt

    providers:
#        hwi:
#            id: hwi_oauth.user.provider
        fos_userbundle:
            id: fos_user.user_provider.username


    firewalls:
        main:
            anonymous: ~
            logout: ~
            form_login:
                csrf_token_generator: security.csrf.token_manager
        secured_area:
            anonymous: ~
            oauth:
                resource_owners:
                    auth0: "/auth0/callback"
                login_path:        /login
                use_forward:       false
                failure_path:      /login

                oauth_user_provider:
                    service: hwi_oauth.user.provider
            logout:
                path:   /auth0/logout
                target: /

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/secured, roles: ROLE_OAUTH_USER }